### ISSUE TITLE
Internal TLS certificate are mounted in the wrong path

### ISSUE THREAD

**Issue by cgiraldo** [passbolt/charts-passbolt#100]
Related with #80 

Passbolt container Image uses `/etc/ssl/certs/certificate.crt` and `/etc/ssl/certs/certificate.key` (see contents of /etc/nginx/snippets/passbolt-ssl.conf file).

However helm chart mount internal tls certificate in '/etc/ssl/certs/passbolt/server.crt' and '/etc/ssl/certs/passbolt/server-key.pem'.

https://github.com/passbolt/charts-passbolt/blob/4bde003871a33ee1ff861acbdf0e09820e0214c1/templates/deployment.yaml#L148

Since It is common to use `tls.key` and `tls.crt`  as the keys in kubernetes tls secrets, I propose to use a projected volume to be able to mount the kubernetes secret  in the target path:  `/etc/ssl/certs/certificate.crt` and `/etc/ssl/certs/certificate.key`

example:
```
    volumeMounts:
            - mountPath: /etc/ssl/certs/certificate.crt
              name: sec-tls
              readOnly: true
              subPath: certificate.crt
            - mountPath: /etc/ssl/certs/certificate.key
              name: sec-tls
              readOnly: true
              subPath: certificate.key
...
      volumes:
      - name: sec-tls
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: tls.crt
                path: certificate.crt
              name: {{ include "passbolt.container.tls.secretName" (dict "name" $Name "tls" .Values.app.tls ) }}
          - secret:
              items:
              - key: tls.key
                path: certificate.key
              name: {{ include "passbolt.container.tls.secretName" (dict "name" $Name "tls" .Values.app.tls ) }}
```

The helper that generate the internal-certs must also be updated to use `tls.crt`and `tls.key`.

https://github.com/passbolt/charts-passbolt/blob/4bde003871a33ee1ff861acbdf0e09820e0214c1/templates/_helpers.tpl#L267-L268

With this changes, I was able to deploy passbolt with GatewayAPI TLSPassthrough and an external certificate provided by cert-manager.

If you found it a good solution I can make a pull-request with the changes.
