### ISSUE TITLE
Specify Redis StorageClass in values.yaml

### ISSUE THREAD

**Issue by adegoodyer** [passbolt/charts-passbolt#27]
Hi, in values.yaml.. would it be possible to specify the storageClass for Redis similar to the way in which it is done for MariaDB?

We're deploying into EKS and use a multitude of different StorageClasses for EFS and EBS so are unable to rely on using the default.

Great project btw!

**Comment by dlen** [comment]
closing this feel free to reopen if needed

**Comment by adegoodyer** [comment]
Fab thank you!

I'd tried it with the wrong config earlier..
```
# incorrect
redis:
  persistence:
    enabled: true
    storageClass: "aws-passbolt-demo-redis"
```

After viewing the bitnami/redis default [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml) I was able to use the correct configuration.
```
#correct
redis:
  global:
    storageClass: "aws-passbolt-demo-redis"
```

Thank you for the quick response, much appreciated.
