### ISSUE TITLE
Install passbolt with an existing Postgresql server

### ISSUE THREAD

**Issue by nurzhanbm** [passbolt/charts-passbolt#81]
Hi!

Followed the instructions: [Install passbolt with an existing Postgresql server](https://www.passbolt.com/blog/passbolt-helm-chart-now-supports-postgresql).  I configured in the [values.yam](https://github.com/passbolt/charts-passbolt/blob/main/values.yaml):

```
mariadbDependencyEnabled: false
app:
  database:
    kind: postgresql
passboltEnv:
  plain:
    DATASOURCES_DEFAULT_HOST: 10.15.132.69
    DATASOURCES_DEFAULT_PORT: 5432
    KUBECTL_DOWNLOAD_CMD: curl --proxy example.com:8080 -LO "https://dl.k8s.io/release/$(curl -L --proxy example.com:8080 -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
```

I got an error:

$ helm install passbolt passbolt/passbolt -f  ~/passbolt/values.yaml
Error: INSTALLATION FAILED: YAML parse error on passbolt/templates/deployment.yaml: error converting YAML to JSON: yaml: line 66: found character that cannot start any token

I tried to install again with quotes:

```
passboltEnv:
  plain:
    DATASOURCES_DEFAULT_HOST: "10.15.132.69"
    DATASOURCES_DEFAULT_PORT: "5432"
```

Got another error:
Error: INSTALLATION FAILED: 1 error occurred:
        * Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.initContainers.env.value of type string

Kubernetes version
v1.24.0-2566+5157800f2a3bc3-dirty
