### ISSUE TITLE
Helm chart upgrade to AppVersion 4.9.9.1-ce from 4.5.2.1-ce failed during ingress patch

### ISSUE THREAD

**Issue by lgromb** [passbolt/charts-passbolt#93]
Hello,

I'm having an issue upgrading the chart from 4.5.2.1-ce to 4.9.9.1-ce. It seems like some of the values changed. Here's the concerned part : 

values.yaml
```
ingress:
  enabled: true
  className: nginx-local
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 123m
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
    - host: passbolt.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - autogenerate: false
      existingSecret: wildcard-example
      hosts:
        - passbolt.example.com
```

Helm template renders : 
```
 helm template . -s templates/ingress.yaml -f ../../k8s/apps/passbolt/values.yaml --debug
install.go:224: 2024-11-14 13:52:16.655662 +0100 CET m=+0.049543459 [debug] Original chart version: ""
install.go:241: 2024-11-14 13:52:16.655901 +0100 CET m=+0.049782626 [debug] CHART PATH:
---
# Source: passbolt/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-passbolt-ing-common
  labels:
    helm.sh/chart: passbolt-1.2.0
    app.kubernetes.io/version: "4.9.1-1-ce"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: passbolt
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/action: common
    app.kubernetes.io/type: ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 123m
spec:
  ingressClassName: nginx-local
  tls:
    - hosts:
        - "passbolt.example.com"
      secretName: wildcard-oci
  rules:
    - host: "passbolt.oci.fr"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-passbolt
                port:
                  name:
```

As you can see, it's missing the last part concerning the backend. Looking at the chart, it should compute : 

```
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $Name }}
                port:
                  name: {{ .port }}
              {{- else }}
              serviceName: {{ $Name }}
              servicePort: {{ .port }}
              {{- end }}
```

I saw here : https://github.com/helm/helm/issues/12072#issuecomment-1565081713 that GitVersion is undocumented and shouldn't be used but I don't think that's the issue, since `pathType` is rendered as it should be using the same field.

k8s cluster is 1.31+

Thanks !

**Comment by lgromb** [comment]
It's a typo from me who hadn't check the updated default values from Passbolt.

See https://raw.githubusercontent.com/passbolt/charts-passbolt/main/values.yaml

I'm missing a `port:` in this part :

```
  hosts:
    - host: passbolt.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
```

Added it as per the default values and it renders fine now, and the upgrade is a success.

Closing this issue.
