### ISSUE TITLE
Utilizing MetalLB

### ISSUE THREAD

**Issue by dingerkingh** [passbolt/charts-passbolt#97]
Hi There!

I am trying to use MetalLB to assign a loadbalanced IP. I am using the following:

service:
  annotations: {}
  ports:
    http:
      name: http
      port: 80
      targetPort: 80
    https:
      name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 192.168.0.14

However - when it comes to life it is getting an IP of 192.168.0.11 - which is also an IP in my MetalLB IP Range. Is specifying loadBalancerIP supported? I am new to this - so quite possible I am making a mistake. Thanks for any feedback you might be able to provide!

**Comment by Tecnobutrul** [comment]
Hello @dingerkingh! Thank you for using the passbolt helm chart. Right now, this charts doesn't support this kind of service configuration. This will take a while to us to find the time to add a new feature to allow you using these kind of services (you can always open  a PR if you think you know how to solve it).

A temporary solution, while you wait for the new feature, would be to create a service with your needed configuration instead of using the one we are providing. You are plenty of examples on k8s [documentation](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/) to do so.

**Comment by Tecnobutrul** [comment]
Our service is not assigning that IP. I have never tried metalLb but I guess what is happening is that the chart is trying to create a load balancer with an empty loadBalancerIp field (because we don't support it yet) so the metalLb api is assigning one from the range that you configured.

**Comment by hvolpers** [comment]
Hi,

you cannot set the ip address, but request it using annotations

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.io/loadBalancerIPs: 192.168.0.14
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```
(https://metallb.universe.tf/usage/)

hth
